name: country_pick

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  #google fonts for styled_text
  google_fonts: ^3.0.1

  flutter_svg: ^1.1.6

flutter:

  assets:
    - assets/flags/
    - assets/icons/
